#ifndef GPIO_ALT_FUNCS_H
#define GPIO_ALT_FUNCS_H

#ifdef __cplusplus
	extern "C" {
#endif

#include "gpio.h"

typedef struct
{
	const gpio_alternate_function_enum valid_alt_functions[GPIO_PIN_MAX_VALUE][GPIO_MAX_ALT_FUNCS_PER_PIN];
}gpio_valid_alt_funcs_t;

/**
 * Alternate Function Validity Arrays
 */
static const gpio_valid_alt_funcs_t GPIO_PORT_A_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_B_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_C_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_D_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_E_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_F_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_G_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_H_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},	    //PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},	    //PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_I_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_J_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT} 	//PIN 15
	}
};
static const gpio_valid_alt_funcs_t GPIO_PORT_K_ALT_FUNCS =
{
	.valid_alt_functions =
	{
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 0
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 1
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 2
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 3
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 4
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 5
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 6
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_EVENT_OUT},	//PIN 7
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},	    //PIN 8
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},	    //PIN 9
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},	    //PIN 10
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},	    //PIN 11
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},    	//PIN 12
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},	    //PIN 13
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV},	    //PIN 14
		{GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV, GPIO_AF_INV} 	    //PIN 15
	}
};

static const gpio_valid_alt_funcs_t* const GPIO_ALT_FUNCS[] =
{
		(&GPIO_PORT_A_ALT_FUNCS),
		(&GPIO_PORT_B_ALT_FUNCS),
		(&GPIO_PORT_C_ALT_FUNCS),
		(&GPIO_PORT_D_ALT_FUNCS),
		(&GPIO_PORT_E_ALT_FUNCS),
		(&GPIO_PORT_F_ALT_FUNCS),
		(&GPIO_PORT_G_ALT_FUNCS),
		(&GPIO_PORT_H_ALT_FUNCS),
		(&GPIO_PORT_I_ALT_FUNCS),
		(&GPIO_PORT_K_ALT_FUNCS)
};

#ifdef __cplusplus
}
#endif

#endif //GPIO_ALT_FUNCS_H
