#ifndef SYSTEM_CONFIG_H
#define SYSTEM_CONFIG_H

#ifdef __cplusplus
	extern "C" {
#endif

#include <stdint.h>

/**
 * EXTI LINE 
 * 	
 * 	- Only including EXTI lines that are related to SYSCFG
*/
typedef enum SYSCFG_EXTI_LINE_ENUM
{
	SYSCFG_EXTI_LINE_0 = 0U,
	SYSCFG_EXTI_LINE_1,
	SYSCFG_EXTI_LINE_2,
	SYSCFG_EXTI_LINE_3,
	SYSCFG_EXTI_LINE_4,
	SYSCFG_EXTI_LINE_5,
	SYSCFG_EXTI_LINE_6,
	SYSCFG_EXTI_LINE_7,
	SYSCFG_EXTI_LINE_8,
	SYSCFG_EXTI_LINE_9,
	SYSCFG_EXTI_LINE_10,
	SYSCFG_EXTI_LINE_11,
	SYSCFG_EXTI_LINE_12,
	SYSCFG_EXTI_LINE_13,
	SYSCFG_EXTI_LINE_14,
	SYSCFG_EXTI_LINE_15
}SYSCFG_EXTI_LINE_ENUM;

/**
 * GPIO PORT
*/
typedef enum SYSCFG_GPIO_PORT_ENUM
{
	SYSCFG_GPIO_PORT_A = 0U,
	SYSCFG_GPIO_PORT_B,
	SYSCFG_GPIO_PORT_C,
	SYSCFG_GPIO_PORT_D,
	SYSCFG_GPIO_PORT_E,
	SYSCFG_GPIO_PORT_F,
	SYSCFG_GPIO_PORT_G,
	SYSCFG_GPIO_PORT_H,
	SYSCFG_GPIO_PORT_I,
	SYSCFG_GPIO_PORT_J,
	SYSCFG_GPIO_PORT_K
}SYSCFG_GPIO_PORT_ENUM;

#ifdef __cplusplus
}
#endif //__cplusplus

#endif //SYSTEM_CONFIG_H